Feat : MapModal 컴포넌트 기능 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #112
Opened 2024-10-01 01:52 UTC by jymaeng1234

## 📝 Summary

공연장 정보(장소명,주소,전화번호,지도)를 표시하는 컴포넌트 입니다.

## ✨ Changes

- MapModal 컴포넌트를 추가했습니다.
- 환경변수에서 카카오맵 API KEY를 불러오는 부분을 추가했습니다.

## 🖼️ Screenshots

![image](https://github.com/user-attachments/assets/d0428403-d2f1-45d2-aed8-ea3aec8225dc)

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/93

## 💬 Comments

- 카카오 개발자 사이트에서 API KEY를 발급받아야 합니다. (https://apis.map.kakao.com/web/guide/)
- 환경 변수에 VITE_KAKAO_MAP_API_KEY 키를 등록해야합니다.
- 모달창 크기 조절이 가능합니다. 
  단, 최소 가로 800px 이상, 세로 600px 이상으로 설정되어있습니다. 
<img width="476" alt="image" src="https://github.com/user-attachments/assets/93bfd954-d64d-422b-abb9-fe5e6b5a329f">

2024-10-01 08:38 UTC, bluedog129 approved these changes, later dismissed

2024-10-02 05:02 UTC, shlee9999 requested changes

2024-10-02 05:02 UTC, shlee9999 commented on src/components/MapModal/styles.ts
> +    border: 1px solid ${props => props.theme.colors.gray};
이 부분 컨벤션에 맞게 바꾸어주세요!

2024-10-02 05:02 UTC, shlee9999 commented on src/components/MapModal/styles.ts
> +    color: ${props => props.theme.colors.gray};
이 부분도요!

2024-10-02 08:30 UTC, jymaeng1234 commented on src/components/MapModal/styles.ts
> +    border: 1px solid ${props => props.theme.colors.gray};
코멘트 주신 부분 반영했습니다.

2024-10-02 08:31 UTC, jymaeng1234 commented on src/components/MapModal/styles.ts
> +    color: ${props => props.theme.colors.gray};
이부분도 반영했습니다!

2024-10-04 01:42 UTC, shlee9999 approved these changes, later dismissed

2024-10-04 02:20 UTC, thsk3 approved these changes, later dismissed

2024-10-04 03:20 UTC, shlee9999 approved these changes

2024-10-04 03:21 UTC, merged