Feat: RankIcon 컴포넌트 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #117
Opened 2024-10-01 03:49 UTC by se0kcess

## 📝 Summary

RankIcon 컴포넌트 추가
## ✨ Changes

- rank 가 1,2,3위 일 경우 theme.ts의 yellow, silver, bronze 컬러 적용

## 🖼️ Screenshots

![image](https://github.com/user-attachments/assets/12fc55d2-0047-4f0b-ad5d-503470128391)

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/114

## 💬 Comments

2024-10-01 06:42 UTC, shlee9999 requested changes

2024-10-01 06:42 UTC, shlee9999 commented on src/components/RankIcon/styles.ts
> +};
이 부분은 utils 폴더에 ts파일을 만들어서 넣어주세요!

2024-10-01 06:42 UTC, shlee9999 commented on src/components/RankIcon/styles.ts
> +  color: ${props => props.color};
color: ${({ color }) => color}; 형태로 바꿔주세요!

2024-10-02 01:14 UTC, se0kcess commented on src/components/RankIcon/styles.ts
> +};
수정했습니다!

2024-10-02 02:14 UTC, jymaeng1234 approved these changes

2024-10-02 02:32 UTC, thsk3 approved these changes

2024-10-02 05:23 UTC, shlee9999 approved these changes

2024-10-02 05:23 UTC, merged