Feat: NoResultIcon 컴포넌트 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #121
Opened 2024-10-01 05:51 UTC by se0kcess

## 📝 Summary

NoResultIcon 컴포넌트 추가
## ✨ Changes

- noResultIcon svg 추가
- 컴포넌트 디자인

## 🖼️ Screenshots

<img width="394" alt="image" src="https://github.com/user-attachments/assets/e976d52b-c189-4714-8718-c94f8d315741">

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue:  https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/118

## 💬 Comments

2024-10-01 07:03 UTC, shlee9999 requested changes

2024-10-01 07:03 UTC, shlee9999 commented on src/components/NoResultIcon/index.tsx
> +export const NoResultIcon = () => {
네이밍이 좀 직관적이지 않은 것 같습니다! AI한테 네이밍만 바꿔달라고 해봤어요
참고하셔서 변경 부탁드려요😃 
```tsx
export const NoSearchResultsMessage = () => {
  return (
    <S.NoSearchResultsContainer>
      <S.NoResultsIcon src="src/assets/imgs/no-results-icon.svg" alt="No results icon" />
      <S.NoResultsText>검색 결과가 존재하지 않습니다.</S.NoResultsText>
    </S.NoSearchResultsContainer>
  );
};
```

2024-10-02 01:27 UTC, se0kcess commented on src/components/NoResultIcon/index.tsx
> +export const NoResultIcon = () => {
넵! 수정했습니다

2024-10-02 02:35 UTC, thsk3 approved these changes

2024-10-02 05:24 UTC, shlee9999 approved these changes

2024-10-02 05:24 UTC, merged