130-0feature/PaginationButton 컴포넌트 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #134
Opened 2024-10-02 02:31 UTC by bluedog129

## 📝 Summary

페이지네이션 버튼 컴포넌트를 구현했습니다.
## 🖼️ Screenshots

<img width="33" alt="image" src="https://github.com/user-attachments/assets/2badccef-6785-4d7a-9ac0-c6ce9849f93c">
<img width="29" alt="image" src="https://github.com/user-attachments/assets/711e95de-c32c-4a65-a62c-064e92fd69d7">

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: 

## 💬 Comments

2024-10-02 06:07 UTC, shlee9999 requested changes

2024-10-02 06:07 UTC, shlee9999 commented on src/components/PaginationButton/index.tsx
> +  onClick: (number: number) => void;
onClickPaginationButton 으로 바꾸어 주세요!
그리고 매개변수 네이밍이 number보단 page가 좋을 것 같습니다

2024-10-02 06:07 UTC, shlee9999 commented on src/components/PaginationButton/index.tsx
> +
아래 함수 추가하시고, onClick 이벤트에 `onClick={onClick(page)}` 로 넣어주시면 될 거에요!
```js 
onClick = (page:number)=> () =>onClickPaginationButton(page)
```

2024-10-02 06:25 UTC, bluedog129 commented on src/components/PaginationButton/index.tsx
> +  onClick: (number: number) => void;
넵!

2024-10-02 07:15 UTC, shlee9999 requested changes

2024-10-02 07:15 UTC, shlee9999 commented on src/components/PaginationButton/index.tsx
>      <S.PaginationButton $isActive={isActive} onClick={() => onClick(number)}>
여기 onClick에  () => onClick(number) 대신 `onClickPaginationButton(page)` 넣어주시면 댑니다

2024-10-02 07:15 UTC, shlee9999 commented on src/components/PaginationButton/index.tsx
> +export const PaginationButton = ({ number, currentPage, onClickPaginationButton }: PaginationButtonProps) => {
number 말고 page 또는 pageNumber 정도가 좋을 것 같아요!

2024-10-04 03:28 UTC, shlee9999 approved these changes

2024-10-04 03:28 UTC, merged