161-feature/Pagination 컴포넌트 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #163
Opened 2024-10-04 08:44 UTC by bluedog129

## 📝 Summary

Pagination 컴포넌트를 구현 했습니다.

## 🖼️ Screenshots

https://github.com/user-attachments/assets/6b40618c-9c90-48fb-889c-816483058dfb

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: #161

## 💬 Comments

2024-10-04 11:58 UTC, shlee9999 commented
## 버그
![{159C1C29-C5DF-47A1-8AF0-D9C039F61746}](https://github.com/user-attachments/assets/524ab493-0087-47c7-9d89-5c26dd7acb5a)
3번 페이지를 클릭했는데 다음 페이지들이 나오지 않네요 ㅠㅠ

2024-10-04 12:04 UTC, shlee9999 commented
## TotalPages
다름이 아니라 API에서 TotalPages에 관한 정보를 넘겨주질 않네요ㅠㅠ
아무래도 초기 5개 페이지 정도를 한 번에 불러오고, 페이지를 넘길 때마다 다음 페이지로 API를 요청한 후 응답 배열에 아이템이 없으면 끝 페이지로 설정하는 작업 등을 해야 할 것 같습니다. 저희 API가 많이 불친절하다고 생각되네요ㅠ

2024-10-04 12:11 UTC, shlee9999 requested changes

2024-10-04 12:11 UTC, shlee9999 commented on src/components/Pagination/index.tsx
> +        onClickPaginationButtonCon={onClick}
흐름을 보니 onClickPaginationButton이 더 좋은 것 같습니다!

2024-10-04 12:11 UTC, shlee9999 commented on src/components/Pagination/index.tsx
> +  const [currentPage, setCurrentPage] = React.useState(defaultPage);
React.useState가 아닌 useState를 사용해주세요~~
import React from 'react'가 아닌 import { useState } from 'react'; 로 해주시면 됩니다!

2024-10-04 12:11 UTC, shlee9999 commented on src/components/Pagination/index.tsx
> +  React.useEffect(() => {
이것도 useState랑 마찬가지로 바꿔주세요!

2024-10-06 08:38 UTC, bluedog129 commented on src/components/Pagination/index.tsx
> +        onClickPaginationButtonCon={onClick}
넵 수정했습니다!

2024-10-06 08:41 UTC, bluedog129 commented on src/components/Pagination/index.tsx
> +  React.useEffect(() => {
넵 둘다 변경했습니다!

2024-10-07 00:34 UTC, shlee9999 requested changes

2024-10-07 00:34 UTC, shlee9999 commented on src/components/Pagination/index.tsx
> +  defaultPage: number;
상위 컴포넌트의 currentPage를 나타내서, 네이밍이 좀 애매한 것 같습니다
selectedPage 정도로 할까요??

2024-10-07 00:48 UTC, shlee9999 approved these changes

2024-10-07 00:48 UTC, merged