Feat: RankPage 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #165
Opened 2024-10-04 09:29 UTC by se0kcess

## 📝 Summary

- 장르 필터링: 사용자가 다양한 공연 장르 중 선택할 수 있습니다.
- 기간 필터링: 일간, 주간, 월간 데이터를 선택할 수 있습니다.
- 데이터 fetching: `useBoxOffice` hook을 사용하여 선택된 필터에 따른 데이터를 가져옵니다.
- 데이터 표시: 가져온 데이터를 `PItemContainer` 컴포넌트를 통해 표시합니다.

## ✨ Changes

- useState, useMemo를 활용한 상태 관리 및 성능 최적화
- SquareButtonContainer, FilterButtonContainer, PItemContainer 컴포넌트 활용

## 🖼️ Screenshots

![Uploading image.png…]()

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/136

## 💬 Comments

2024-10-04 09:50 UTC, se0kcess commented
getFormattedDates 함수를 적용해서 현재일로 설정하려고 했는데 적용하면 api가 안불러와지네요.. 해결방법 아시는 분은 공유 부탁드립니다!!

2024-10-04 11:37 UTC, shlee9999 requested changes

2024-10-04 11:37 UTC, shlee9999 commented on src/pages/RankPage/index.tsx
> +type GenreName = keyof typeof genreMap;
이 두 타입을 다른 파일에서도 사용하는 지 피그마에서 한 번 둘러보시고 있다면 types 폴더에 따로 추가해주세요!

2024-10-04 11:37 UTC, shlee9999 commented on src/pages/RankPage/index.tsx
> +const stsPeriods: ('day' | 'week' | 'month')[] = ['day', 'week', 'month'];
이 부분도 다른 부분에서 사용되는지 확인해보시고 있다면 따로 constants, types에 추가해주세요~!

2024-10-04 11:37 UTC, shlee9999 commented on src/pages/RankPage/index.tsx
> +  }, [data, activeGenre]);
`return data?.boxofs?.boxof.map(...) ?? []`
이런 식으로 하는 게 더 간단할 것 같습니다!
뭐가 더 좋고 나쁠 지는 잘 모르겠네요
이런 방법도 있으니 맘에 드시는 거로 하시면 될 듯 합니다!

2024-10-04 11:37 UTC, shlee9999 commented on src/pages/RankPage/index.tsx
> +          <SquareButtonContainer<GenreCode>
제네릭을 사용하셨군요 이것도 좋은 접근인 것 같습니다!
다만 가독성이 떨어진다는 문제가 좀 있네요! 아무래도 태그에도 <, >가 들어가다보니
우선 유지하셔도 괜찮을 것 같습니다~

2024-10-04 11:52 UTC, shlee9999 commented
민석님 getFormattedDates 함수에 문제는 없었는데요, 아마도 저 api가 오늘 늦은 시각에 업데이트 되어 오늘 날짜로는 api를 호출할 수 없는 것 같습니다. 제 생각엔 어제 날짜로 해야 할 것 같아서, getFormattedDates  함수에 yesterday와 tomorrow를 추가해 뒀어요. rebase해서 이걸 사용하시면 될 것 같습니다. 작동 되는 것도 확인 했습니다.

2024-10-04 11:53 UTC, shlee9999 commented
## 버그
일간, 주간, 월간 필터를 누르면 데이터가 불러와지지만, 데이터가 불러와진 이후 해당 필터로 색이 변하지 않는 버그가 있어요

2024-10-05 09:51 UTC, se0kcess commented on src/pages/RankPage/index.tsx
> +type GenreName = keyof typeof genreMap;
types 폴더에 따로 추가해 두었습니다!

2024-10-05 09:52 UTC, se0kcess commented on src/pages/RankPage/index.tsx
> +const stsPeriods: ('day' | 'week' | 'month')[] = ['day', 'week', 'month'];
이 부분은 RankPage 이외에 따로 쓰이지 않는 것 같아 유지했습니다!

2024-10-05 09:52 UTC, se0kcess commented on src/pages/RankPage/index.tsx
> +  }, [data, activeGenre]);
넵 수정했습니다!

2024-10-05 09:54 UTC, se0kcess commented
FilterButton 버그 수정 및 getFormedDates yesterday로 적용 완료했습니다. 1,2,3 순위 공연은 pcard 컴포넌트에 rankicon 적용 예정입니다

2024-10-07 03:44 UTC, shlee9999 requested changes

2024-10-07 03:44 UTC, shlee9999 commented on src/pages/RankPage/index.tsx
> +  }, [data, activeGenre]);
의존성 배열의 `activeGenre`는 제거해도 될 것 같습니다!

2024-10-07 03:47 UTC, shlee9999 approved these changes

2024-10-07 03:47 UTC, merged