Feat : PosterWithDetailInfo 컴포넌트 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #166
Opened 2024-10-06 01:57 UTC by jymaeng1234

## 📝 Summary

-  공연 기본 정보 및 찜하기 버튼, 공유 버튼, 리뷰 폼이 그룹화된 컴포넌트 입니다.

## ✨ Changes

- PosterWithDetail 컴포넌트 생성

## 🖼️ Screenshots

![image](https://github.com/user-attachments/assets/f1d48954-7867-4a6d-8c35-01c3a47fa4a4)

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/146

## 💬 Comments

- isNameInclude 값을 true로 설정할 경우, 공연 이름/ 장르가 함께 표기됩니다.
- PDetailReviewForm 컴포넌트와 PDetailInfo컴포넌트의 스타일 통일 작업이 필요합니다.

2024-10-06 04:28 UTC, shlee9999 requested changes

2024-10-06 04:28 UTC, shlee9999 commented on src/components/PosterWithDetailInfo/index.tsx
> +      <S.PinfoContainer>
i를 대문자로 바꿔주세요!

2024-10-06 04:28 UTC, shlee9999 commented on src/components/PosterWithDetailInfo/index.tsx
> +  poster_width?: string;
camelCase로 바꿔주세요

2024-10-06 04:28 UTC, shlee9999 commented on src/components/PosterWithDetailInfo/index.tsx
> +  url: string;
무슨 src, url인지 변수명에 포함해주세요!

2024-10-06 04:28 UTC, shlee9999 commented
나머지는 Slack에 보내드린 링크 참고하셔서 진행해주세요!

2024-10-06 15:46 UTC, jymaeng1234 commented
코멘트 주신 부분 모두 수정했습니다.

2024-10-07 02:52 UTC, bluedog129 approved these changes

2024-10-07 02:56 UTC, merged