16 feat/header component implemention
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #40
Opened 2024-09-25 06:53 UTC by bluedog129

## 📝 Summary
헤더 컴포넌트를 구현했습니다

## ✨ Changes

- 헤더 컴포넌트의 레이아웃 구성 
- 스타일 적용
- 라우터 적용

## 🖼️ Screenshots
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/5554e505-2862-465b-92de-adac150b7d74">

## 🤔 Checklist

- [x] 코드 컨벤션을 준수했나요?
- [x] 불필요한 콘솔 로그나 주석은 없나요?

## 🔗 References

- Issue: #16 

## 💬 Comments

2024-09-25 07:11 UTC, se0kcess submitted a review, later dismissed

2024-09-25 07:18 UTC, shlee9999 requested changes

2024-09-25 07:18 UTC, shlee9999 commented on src/components/Header/index.tsx
> +          </S.SearchIcon>
아이콘 폰트어썸에 있다면 찾아서 써주세요!
자주 쓰는 아이콘들은 웬만하면 다 있습니다~

2024-09-25 07:31 UTC, bluedog129 commented on src/components/Header/index.tsx
> +          </S.SearchIcon>
넵 변경했습니다!

2024-09-25 07:39 UTC, shlee9999 approved these changes, later dismissed

2024-09-25 07:39 UTC, se0kcess submitted a review, later dismissed

2024-09-25 07:39 UTC, thsk3 submitted a review, later dismissed

2024-09-25 08:45 UTC, jymaeng1234 approved these changes, later dismissed

2024-09-25 08:47 UTC, shlee9999 requested changes

2024-09-25 08:47 UTC, shlee9999 commented on src/components/Header/index.tsx
> +          <S.StyledIcon>
StyledIcon의 용도는 뭔가요?

2024-09-25 08:47 UTC, shlee9999 commented on src/components/Header/styles.ts
> +  color: ${({ theme, isRangking }) => (isRangking ? theme.colors.primary : theme.colors.black)};
isRanked가 좋을 것 같습니다!

2024-09-25 08:56 UTC, bluedog129 commented on src/components/Header/index.tsx
> +          <S.StyledIcon>
과거 이미지파일의 잔재네요 ㅎ..

2024-09-25 08:56 UTC, bluedog129 commented on src/components/Header/styles.ts
> +  color: ${({ theme, isRangking }) => (isRangking ? theme.colors.primary : theme.colors.black)};
넵!

2024-09-26 01:09 UTC, shlee9999 approved these changes

2024-09-26 01:10 UTC, se0kcess approved these changes

2024-09-26 01:10 UTC, merged