38 feature/detailimage component
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #42
Opened 2024-09-25 07:34 UTC by jymaeng1234

## 📝 Summary
공연 상세 정보 이미지를 나타내는 컴포넌트입니다.

## ✨ Changes
-  컴포넌트 구현

## 🖼️ Screenshots
![image](https://github.com/user-attachments/assets/c4f6f6e2-9c94-43f8-882e-7e2397529569)

## 🤔 Checklist
- [x] 코드 컨벤션을 준수했나요?
- [x] 충분한 테스트를 작성했나요?
- [x] 모든 테스트가 통과하나요?
- [x] 불필요한 콘솔 로그나 주석은 없나요?

## 🔗 References
- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/38

## 💬 Comments

Poster component와 동일한 기능입니다

2024-09-25 07:43 UTC, thsk3 submitted a review, later dismissed

2024-09-26 00:30 UTC, shlee9999 requested changes

2024-09-26 00:30 UTC, shlee9999 commented on src/components/DetailImage/styles.ts
> +  max-height: ${props => props.height}px;
1. CSS가 무슨 의도인지 이해가 잘 안갑니다ㅜㅜ 
    DetailImage의 경우 이미지의 비율을 맞춰줘야 하기 때문에 width만 100% 설정하면 될 것 같습니다.
    height, max-width, max-height는 안 넣어주셔도 될 것 같아요.
2. props 받아오는 거 오늘 아침에 말씀드린 컨벤션에 따라 수정 부탁드려요!

2024-09-26 00:30 UTC, shlee9999 commented on src/components/DetailImage/index.tsx
> +export const DetailImage = ({ src, width = 1280, height = 1500 }: DetailImageProps) => {
아래 코멘트에서 말씀드렸듯이 width를 100%로만 설정해주면 될 것 같습니다. 따라서 props로 src만 받아오면 될 것 같아요!
페이지 자체에 max-width 1280을 줄 거기 때문에 100%면 충분할 것 같습니다 ㅎㅎ

2024-09-26 00:32 UTC, bluedog129 submitted a review, later dismissed
LGTM

2024-09-26 03:45 UTC, jymaeng1234 commented on src/components/DetailImage/styles.ts
> +  max-height: ${props => props.height}px;
알겠습니다 수정하겠습니다.

2024-09-26 05:07 UTC, shlee9999 approved these changes

2024-09-26 05:12 UTC, thsk3 approved these changes

2024-09-26 05:15 UTC, merged