18 feat/sharebutton component
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #46
Opened 2024-09-26 00:35 UTC by jymaeng1234

## 📝 Summary
공유버튼
아이콘을 클릭하면 지정된 경로가 복사됩니다.

## ✨ Changes

- 

## 🖼️ Screenshots

![image](https://github.com/user-attachments/assets/965cf344-9501-462b-913c-314c84a172a6)

## 🤔 Checklist

- [x] 코드 컨벤션을 준수했나요?
- [x] 불필요한 콘솔 로그나 주석은 없나요?

## 🔗 References

- Issue: 

## 💬 Comments

사용 방법 : 공유할 경로(현재 페이지 url) 정보를 넣어줍니다.
![image](https://github.com/user-attachments/assets/75f5313a-3452-46b9-bd7a-ad244a6db057)

2024-09-26 01:51 UTC, shlee9999 requested changes

2024-09-26 01:51 UTC, shlee9999 commented on src/components/ShareButton/index.tsx
> +  const handleCopy = () => {
이전에 onClick으로 하기로 했던 것 같아요!

2024-09-26 01:51 UTC, shlee9999 commented on src/components/ShareButton/index.tsx
> +    </S.ShareButton>
한 줄로 줄일 수 있을 것 같습니다! Wiki -> FontAwesome 페이지 하단에 적어둔 내용처럼 해주시면 될 것 같아요~
<S.ShareButton icon={} onClick={}/> 형태로 해주시면 감사하겠습니다!

2024-09-26 01:51 UTC, shlee9999 commented on src/components/ShareButton/styles.ts
> +    }
왜 P16으로 받아와서 스타일링 하신 건지 모르겠어요!

2024-09-26 02:14 UTC, jymaeng1234 commented on src/components/ShareButton/index.tsx
> +    </S.ShareButton>
네 참고하겠습니다!

2024-09-26 05:09 UTC, shlee9999 approved these changes, later dismissed

2024-09-27 01:11 UTC, se0kcess approved these changes, later dismissed

2024-09-27 01:11 UTC, thsk3 submitted a review, later dismissed

2024-09-27 01:11 UTC, ghost commented on src/components/ShareButton/styles.ts
> +    color: ${props => props.theme.colors.primary};
props를 아래처럼 사용하기로 했던 것 같아요!
`color: ${({theme}) => theme.colors.primary}`

2024-09-27 01:16 UTC, thsk3 approved these changes

2024-09-27 01:16 UTC, shlee9999 approved these changes

2024-09-27 01:17 UTC, merged