Feat : detail-image-container component 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #60
Opened 2024-09-26 06:18 UTC by jymaeng1234

## 📝 Summary
이미지 목록을 입력하면 세로 방향으로 이미지를 출력하는 컴포넌트

## ✨ Changes
- detailImage 목록 컨테이너 구현

## 🖼️ Screenshots
![image](https://github.com/user-attachments/assets/6a0d3f44-07f3-4226-a6d8-0882dfee85c0)

## 🤔 Checklist
- [ ] 코드 컨벤션을 준수했나요?
- [ ] 불필요한 콘솔 로그나 주석은 없나요?

## 🔗 References
- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/34

## 💬 Comments
사용 예시
![image](https://github.com/user-attachments/assets/19d1b65a-1517-4b40-b028-818f14485d98)

2024-09-26 06:34 UTC, thsk3 submitted a review, later dismissed

2024-09-26 08:06 UTC, shlee9999 requested changes

2024-09-26 08:06 UTC, shlee9999 commented on src/components/DetailImageContainer/index.tsx
> +        <DetailImage key={index} src={detailImg.src} />
key에 고유한 값(id 등)을 넣어주세요!

2024-09-26 08:06 UTC, shlee9999 commented on src/components/DetailImageContainer/styles.ts
> +  align-items: center;
CSS는 우선 비워둬도 괜찮을 것 같습니다!
flex를 사용하게 되면 생각보다 원하는 대로 레이아웃이 잡히지 않을 때가 있어서요
flex는 나중에 필요해진다면 추가하는 게 좋을 것 같습니다!

2024-09-27 00:17 UTC, jymaeng1234 commented on src/components/DetailImageContainer/index.tsx
> +        <DetailImage key={index} src={detailImg.src} />
반영하겠습니다.

2024-09-27 00:17 UTC, jymaeng1234 commented on src/components/DetailImageContainer/styles.ts
> +  align-items: center;
네! 알겠습니다.

2024-09-27 01:27 UTC, thsk3 approved these changes

2024-09-27 02:48 UTC, shlee9999 approved these changes

2024-09-27 02:49 UTC, merged