Feat: FilterButtonContainer 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #80
Opened 2024-09-27 07:29 UTC by se0kcess

## 📝 Summary

FilterButtonContainer 컴포넌트 추가

## ✨ Changes

- FilterButton 컴포넌트 배치가능한 컨테이너 컴포넌트 구현
-
## 🖼️ Screenshots

<img width="294" alt="image" src="https://github.com/user-attachments/assets/d6f93f11-44ad-4582-9326-5291a0527518">

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/74

## 💬 Comments

Seperator 배치하는 과정에서 위치는 정렬이 됐는데 회색 구분 선이 보이지 않아 일단 border로 나타나게 했습니다 괜찮은 배치 방법 아시는 분 의견 남겨주시면 감사하겠습니다ㅠㅠ

2024-09-27 08:25 UTC, shlee9999 requested changes

2024-09-27 08:25 UTC, shlee9999 commented on src/components/FilterButtonContainer/styles.ts
> +  border: 1px solid ${({ theme }) => theme.colors.gray};
민석님 이 border 부분 지워주시고, Seperator에서 grey로 되어있는 걸 gray로 바꿔주시겠어요?
그러면 해결될 것 같습니다!

2024-09-27 08:25 UTC, shlee9999 commented on src/components/FilterButtonContainer/index.tsx
> +          <FilterButton key={index} text={text} $isActive={index === activeItem} onClick={() => setActiveItem(index)} />
[주연님 코드](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/pull/66/files)와 동일하네요
참고하셔서 onClick부분을 화살표 함수 2개로 해보시겠어요?

2024-09-27 08:50 UTC, se0kcess commented on src/components/FilterButtonContainer/styles.ts
> +  border: 1px solid ${({ theme }) => theme.colors.gray};
아하 오타 때문이었군요! 수정하니 정상 동작해서 커밋 했습니다!

2024-09-27 09:06 UTC, se0kcess commented on src/components/FilterButtonContainer/index.tsx
> +          <FilterButton key={index} text={text} $isActive={index === activeItem} onClick={() => setActiveItem(index)} />
넵 이전 코드들도 이중 화살표 함수 형태로 변경했습니다!
코드 재사용성 때문에 이렇게 사용하는 건가요?? 사용목적이 궁금합니다!

2024-09-30 06:29 UTC, shlee9999 requested changes

2024-09-30 06:29 UTC, shlee9999 commented on src/components/SquareButtonContainer/index.tsx
>    const [activeButtonId, setActiveButtonId] = useState<string | null>(buttonList[0]?.id || null);
useState(buttonList[0]?.id || '') 로 해주시면 될 것 같아요

2024-09-30 06:29 UTC, shlee9999 commented on src/components/SquareButtonContainer/index.tsx
>    buttonList: Array<ButtonItem>;
`ButtonItem[]` 로 해주세요!

2024-09-30 08:18 UTC, shlee9999 requested changes

2024-09-30 08:18 UTC, shlee9999 commented on src/components/SquareButtonContainer/index.tsx
> +  const [activeButtonId, setActiveButtonId] = useState<string>(buttonList[0]?.id || '');
제네릭 string을 지워주세요!

2024-10-01 02:13 UTC, shlee9999 approved these changes

2024-10-01 02:29 UTC, jymaeng1234 approved these changes

2024-10-02 00:40 UTC, merged