Feat: HeartButton 컴포넌트 구현
prgrms-fe-devcourse/NFE1-2-LocalStage pull request #83
Opened 2024-09-27 08:37 UTC by se0kcess

## 📝 Summary

관심있는 공연에 추가 기능이 있는 HeartButton 컴포넌트 추가

## ✨ Changes

- props로 클릭 상태를 받아와서 클릭 시 아이콘 내부 color를 primary color로 변경

## 🖼️ Screenshots

[클릭 전]
<img width="157" alt="image" src="https://github.com/user-attachments/assets/0eb63b6f-f18d-47cf-b490-a7a86e187064">

[클릭 후]
<img width="157" alt="image" src="https://github.com/user-attachments/assets/c237430b-d207-4012-b1ca-d87907b612a9">

## ✅ PR Checklist

- [ ] 하나의 목적을 가진 PR입니다.
- [ ] 코딩 컨벤션과 스타일 가이드를 준수합니다. [📌Conventions](https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/wiki/%F0%9F%93%8CConventions)
- [ ] 불필요한 코드 중복이 없습니다.
- [ ] 컴포넌트의 책임이 단일합니다.
- [ ] 리액트 훅을 올바르게 사용했습니다.
- [ ] 민감한 정보를 포함하지 않았습니다.
- [ ] 불필요한 콘솔 로그나 주석을 포함하지 않았습니다.
- [ ] 컴포넌트 key값에 고유한 값을 할당했습니다.

## 🔗 References

- Issue: https://github.com/prgrms-fe-devcourse/NFE1-2-LocalStage/issues/82

## 💬 Comments

2024-09-30 02:32 UTC, jymaeng1234 submitted a review, later dismissed

2024-09-30 06:34 UTC, shlee9999 requested changes

2024-09-30 06:34 UTC, shlee9999 commented on src/components/HeartButton/index.tsx
> +  const [isClicked, setIsClicked] = useState(initialClicked);
변수 네이밍 isActive 또는 isFilled 가 더 좋을 것 같습니다!

2024-09-30 06:34 UTC, shlee9999 commented on src/components/HeartButton/index.tsx
> +export const HeartButton = ({ initialClicked = false, onClick }: HeartButtonProps) => {
아래 코멘트랑 비슷한 맥락으로 initialClicked도 네이밍을 바꾸는 게 좋아보여요!

2024-09-30 08:36 UTC, shlee9999 requested changes

2024-09-30 08:36 UTC, shlee9999 commented on src/components/HeartButton/index.tsx
> +    setIsFilled(newFilledState);
이전 상태값 기반으로 업데이트하기

2024-09-30 08:36 UTC, shlee9999 commented on src/components/HeartButton/styles.ts
> +  color: ${({ theme, $isClicked }) => ($isClicked ? theme.colors.primary : theme.colors.gray)};
여기도 $isClicked -> $isFilled로 바꿔주셔야 할 것 같아요!

2024-10-01 05:46 UTC, jymaeng1234 approved these changes, later dismissed

2024-10-01 08:51 UTC, shlee9999 commented on src/components/HeartButton/index.tsx
> +    setIsFilled(newFilledState);
`setIsFilled(prev=>!prev)`

2024-10-02 00:27 UTC, shlee9999 requested changes

2024-10-02 00:27 UTC, shlee9999 commented on src/components/HeartButton/index.tsx
> +  onClick?: (isFilled: boolean) => void;
onClick -> onClickHeartButton 으로 바꾸어 주세요!

2024-10-02 00:27 UTC, shlee9999 commented on src/components/HeartButton/index.tsx
> +  const handleClick = () => {
handleClick -> onClick으로 바꾸어 주세요!

2024-10-02 01:20 UTC, jymaeng1234 approved these changes

2024-10-02 02:15 UTC, shlee9999 approved these changes

2024-10-02 02:16 UTC, merged